### ISSUE TITLE
Duplication in settings

### ISSUE THREAD

**Issue by kmaustral** [joelseq/obsidian-linkstowr#2]
This is duplication appears in my installation. 

<img width="591" alt="image" src="https://github.com/joelseq/obsidian-linkshelf/assets/73867063/04b134f0-b35c-43ac-a986-208eea394670">

**Comment by joelseq** [comment]
Thanks for reporting, @kmaustral! I'm not sure what changed recently as I hadn't noticed this issue before :sweat_smile: but it should be fixed now in the 0.2.2 release!

**Comment by kmaustral** [comment]
Thanks. That has fixed the duplication, but I still can't get it to work. I've double-checked the settings and I get a message that the sync is successful, but nothing appears in the designated folder and I see that the links haven't been deleted from the Chrome extension yet.

**Comment by joelseq** [comment]
Looking at some of the traces from my server I see some authentication related errors  but not sure if that's from your requests. In case you haven't already tried it could you try to generate a new token and paste that into both the Chrome extension settings (you can click the gear icon and then click "Clear token" to add a new one) and the Obsidian plugin settings? You might also want to make sure that there are no extra spaces at the start or end of the token as that can cause it to fail as well.

Just to clarify my understanding, when you say "I see that the links haven't been deleted from the Chrome extension yet" do you mean to say that the popup window doesn't close once you click "Save Link"? If that's the case then I think that the token for the Chrome extension is what is failing and the Obsidian plugin one might be valid otherwise you wouldn't get a "Sync successful" notification.

**Comment by kmaustral** [comment]
Hi Joel,

I tried with a new token but that didn't work. I use what is copied into
clipboard when clicking the copy button, which seems right.

The popup window closes when I Save Link, but I do see the previous links
that I had saved on that window. They haven't been cleared yet.

The "linkshelf sync successful" message in Obsidian appears almost
immediately after selecting the sync links command.

**Comment by joelseq** [comment]
Okay I think I know what's going on. There's another Chrome extension that's also called LinkShelf which from looking at the screenshots appears to show the previous links that were saved. 

[This LinkShelf](https://chrome.google.com/webstore/detail/linkshelf/ahppmgflbaeiphlkkgngijgmfapabgee) is the right Chrome extension to install. It should not be showing any previously saved links (though that might be an interesting feature to add later on).

**Comment by kmaustral** [comment]
Yes, that was the issue. I couldn't find a link to that specific extension
on your site, so others might have this issue too.

Great. It's good that you have a keyboard shortcut for it as well.

I'll give it a try and let you know if any other issues come up.

**Comment by joelseq** [comment]
Thanks for the suggestion! That's definitely something I should add to the site to avoid confusion
